server:
  port: 8080

spring:
  application:
    name: service-ticket
  datasource:
    url: jdbc:h2:mem:ticketdb
    driver-class-name: org.h2.Driver
    username: ${env.H2_USERNAME}
    password: ${env.H2_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:19092
      - localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jackson:
    serialization:
      write-dates-as-timestamps: false
